site_name: Advanced C Programming Notes
theme:
  name: material
  favicon: assets/logo.png

  # Option for Footer
  features:
    - navigation.footer

  #color pallate for light and dark
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode


# Social Media Icons
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/AatizGhimire
      name: LinkedIn Profile
    - icon: fontawesome/brands/github 
      link: https://github.com/AatizGhimire
      name: Github Profile
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Aatiz-Ghimire
      name: Research Gate Profile
    - icon: fontawesome/brands/google
      link: https://scholar.google.com/citations?hl=en&user=ooQzSTcAAAAJ
      name: Google Scholar's Profile

copyright: Copyright &copy; 2015 - 2023 Aatiz Ghimiré


# Math JX Support for LaTeX equations:

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
